#!/usr/bin/env python3
"""Regenerate docs/database.md and docs/api.md.

``database.md`` comes from ``schema.py`` (the DDL the server actually creates)
plus ``tools/access_reference.py`` (what the original Access database has), so
the document can never drift away from the running code.

Usage::

    python3 server/src/tools/export_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SRC_DIR = BASE_DIR.parent
ROOT_DIR = SRC_DIR.parent.parent
DOCS_DIR = ROOT_DIR / "docs"

sys.path.insert(0, str(SRC_DIR))
sys.path.insert(0, str(BASE_DIR))

import access_reference  # noqa: E402
import openapi_spec  # noqa: E402
import schema  # noqa: E402

NOTES = {
    "blog_Article": "Blog articles. `log_content0`/`log_content1` are Memo columns; the body auto-splits once it exceeds "
                    "`contentAutoSplitChars`, and `[separator]` splits it by hand.",
    "blog_Category": "Categories. `cat_articleCount` is a counter snapshot the admin backend can recompute.",
    "blog_Comment": "Comments. `comm_authorID=0` marks a guest entry.",
    "blog_Settings": "Site settings. `set_type=0` takes the value from `set_value0` (numeric) and "
                     "`set_type=1` from `set_value1` (string). The column is COLLATE NOCASE "
                     "because the admin `updateSettings` addresses rows with lower case names while the stored names are camel case.",
    "blog_Smilies": "Smilies: `sm_code` is the `[smile]` style marker, `sm_image` the file name.",
    "blog_Trackback": "Trackbacks. `tb_time` is the receive time, `tb_ip` the source address.",
    "blog_User": "Users. `user_password` holds the SHA1(password+salt) hex digest; "
                 "legacy rows may hold an upper case MD5, upgraded after the first successful login. `user_name` is "
                 "COLLATE NOCASE to mirror Access' case insensitive comparison.",
    "blog_UserGroup": "User groups. The five `group_rights` digits are view/post/edit/delete/upload.",
    "blog_VisitorRecord": "Visitor records: once `maxVisitorRecord` is reached the oldest row is overwritten (ring buffer).",
    "blog_WordFilter": "Word filters: `wf_mode=0` replaces, `=1` blocks, and `wf_regExp=1` treats the text as a regular expression.",
    "Guestbook": "The guestbook. The original kept it in a separate gbook.mdb; the port keeps the same table in the one SQLite file.",
}


def database_markdown() -> str:
    lines = [
        "# Data dictionary",
        "",
        "Generated by `server/src/tools/export_docs.py`; do not edit it by hand - "
        "rerun the script after changing `schema.py` or `tools/access_reference.py`.",
        "",
        "Table and column names match the original Access database (`data/blog.mdb`, "
        "`data/gbook.mdb`) exactly. The 'Access type' column comes from parsing the "
        "`.mdb` table definition pages; 'SQLite' is what the server actually creates.",
        "",
        "## Type mapping",
        "",
        "| Access | SQLite | Notes |",
        "|---|---|---|",
        "| Yes/No | INTEGER | 0/1 |",
        "| Byte / Integer / Long Integer | INTEGER | autonumber primary keys use INTEGER PRIMARY KEY AUTOINCREMENT |",
        "| Date/Time | TEXT | `YYYY-MM-DD HH:MM:SS`, local time |",
        "| Text(n) | TEXT | n is the character count (kept in a column comment) |",
        "| Memo | TEXT | unlimited |",
        "",
        "## Indexes",
        "",
        "| Index | Reason |",
        "|---|---|",
    ]
    for statement in schema.INDEXES:
        name = statement.split(" IF NOT EXISTS ")[1].split(" ON ")[0]
        target = statement.split(" ON ")[1].split("(")[0]
        columns = statement.split("(", 1)[1].rstrip(")").replace(" DESC", "")
        lines.append(f"| `{name}` | `{target}({columns})` |")
    lines.append("")

    for table in schema.TABLES:
        reference = {row[0]: row for row in access_reference.ACCESS_TABLES[table]}
        lines.append(f"## {table}")
        lines.append("")
        if table in NOTES:
            lines.append(NOTES[table])
            lines.append("")
        lines.append("| Column | Access type | Length | SQLite | Primary key |")
        lines.append("|---|---|---|---|---|")
        for name, declaration in schema.TABLES[table]:
            access_type, length, _auto, primary = (
                reference[name][1], reference[name][2],
                reference[name][3], reference[name][4],
            )
            sqlite_type = declaration.split()[0]
            if "PRIMARY KEY" in declaration:
                sqlite_type += " PRIMARY KEY"
            if "AUTOINCREMENT" in declaration:
                sqlite_type += " AUTOINCREMENT"
            if declaration.endswith("COLLATE NOCASE"):
                sqlite_type += " COLLATE NOCASE"
            lines.append(
                f"| `{name}` | {access_type} | {length or ''} | {sqlite_type} | "
                f"{'yes' if primary else ''} |"
            )
        lines.append("")

    lines += [
        "## Built-in user groups",
        "",
        "| group_id | Name | group_rights |",
        "|---|---|---|",
    ]
    for group_id, name, rights in schema.BUILTIN_GROUPS:
        lines.append(f"| {group_id} | {name} | `{rights}` |")
    lines.append("")
    return "\n".join(lines)


def api_markdown() -> str:
    lines = [
        "# API reference",
        "",
        "Generated by `server/src/tools/export_docs.py`; do not edit it by hand - "
        "rerun it after changing the API; this also refreshes `docs/openapi.json`.",
        "",
        f"This list has {len(openapi_spec.ENDPOINTS)} operations. Every response is JSON "
        "(except the trackback ping and RSS); failures return "
        '`{"ok": false, "error": "<lang key>"}`.',
        "",
        "| Method | Path | Summary | Access |",
        "|---|---|---|---|",
    ]
    for method, path, operation in openapi_spec.ENDPOINTS:
        summary = operation.get("summary", "")
        path = openapi_spec.asp_path(path)
        auth = operation.get("security")
        if auth:
            permission = "login required"
        elif "admin" in operation.get("tags", []):
            permission = "admin"
        else:
            permission = "public"
        lines.append(f"| {method.upper()} | `{path}` | {summary} | {permission} |")

    lines += [
        "",
        "## Permission model",
        "",
        "- `blog_UserGroup.group_rights` is five digits: `view` / `post` / `edit` / "
        "`delete` / `upload`。",
        "- `0` means no access, `1` only the user's own objects, `2` and above every object.",
        "- Article visibility: `log_mode` 1 public, 2 needs login, 3 needs `view>=2`, 4 needs `view>=3`; "
        "hidden categories need `view>=2`, and authors can always read their own articles.",
        "- The admin backend additionally requires a second login via `POST /api/admin/login`.",
        "",
        "## Anonymous write endpoints",
        "",
        "Following the original, these write endpoints stay open to anonymous visitors; the handlers enforce the guest group rights:",
        "",
        "- `POST /api/articles/{id}/comments`",
        "- `POST /api/guestbook`",
        "- `GET|POST /trackback/{id}` (the ping arrives from other sites)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    database_path = DOCS_DIR / "database.md"
    api_path = DOCS_DIR / "api.md"
    database_path.write_text(database_markdown(), encoding="utf-8")
    api_path.write_text(api_markdown(), encoding="utf-8")
    print(f"wrote {database_path}")
    print(f"wrote {api_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
