#!/usr/bin/env python3
"""Regenerate docs/database.md and docs/api.md.

``database.md`` is built from ``schema.py`` (the layout the server actually
creates) and ``api.md`` from ``openapi_spec.py``, so neither document can drift
away from the code.

Usage::

    python3 server/src/tools/export_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SRC_DIR = BASE_DIR.parent
ROOT_DIR = SRC_DIR.parent.parent
DOCS_DIR = ROOT_DIR / "docs"

sys.path.insert(0, str(SRC_DIR))
sys.path.insert(0, str(BASE_DIR))

import openapi_spec  # noqa: E402
import schema  # noqa: E402

NOTES = {
    "blog_Article": "Articles. `log_content0`/`log_content1` are the two halves of "
                    "the body: it auto-splits once it exceeds `contentAutoSplitChars`, "
                    "and `[separator]` splits it by hand.",
    "blog_Category": "Categories. `cat_articleCount` is a counter snapshot the admin "
                     "backend can recompute.",
    "blog_Comment": "Comments. `comm_authorID=0` marks a guest entry.",
    "blog_Settings": "Site settings. `set_type=0` takes the value from `set_value0` "
                     "(numeric) and `set_type=1` from `set_value1` (string).",
    "blog_Smilies": "Smilies: `sm_code` is the `[smile]` style marker, `sm_image` the "
                    "file name inside the smilies folder.",
    "blog_Trackback": "Trackbacks. `tb_time` is the receive time, `tb_ip` the source "
                      "address.",
    "blog_User": "Users. `user_password` holds the SHA1(password+salt) hex digest; "
                 "legacy rows may hold an upper case MD5 until the owner logs in once.",
    "blog_UserGroup": "User groups. The five `group_rights` digits are "
                      "view/post/edit/delete/upload.",
    "blog_VisitorRecord": "Visitor records: once `maxVisitorRecord` is reached the "
                          "oldest row is overwritten (ring buffer).",
    "blog_WordFilter": "Word filters: `wf_mode=0` replaces, `=1` blocks, and "
                       "`wf_regExp=1` treats the text as a regular expression.",
    "Guestbook": "Guestbook entries, including the single reply each entry can carry.",
}


def database_markdown() -> str:
    lines = [
        "# Data dictionary",
        "",
        "Generated by `server/src/tools/export_docs.py` from `server/src/schema.py`; "
        "do not edit it by hand - rerun `make docs` after a schema change.",
        "",
        "Table and column names follow the original LBS^2 database (see NOTICE). "
        "The declared type is the app level type: SQLite stores an affinity, so a "
        "declared `TEXT(255)` still lands in a `TEXT` column, and the length is "
        "enforced by the application.",
        "",
        "## Declared type to SQLite",
        "",
        "| Declared | SQLite | Notes |",
        "|---|---|---|",
        "| YESNO | INTEGER | 0/1 |",
        "| BYTE | INTEGER | small integer |",
        "| INTEGER / LONG | INTEGER | autonumber keys use INTEGER PRIMARY KEY AUTOINCREMENT |",
        "| DATETIME | TEXT | `YYYY-MM-DD HH:MM:SS`, local time |",
        "| TEXT(n) | TEXT | n is the maximum character count |",
        "| MEMO | TEXT | unlimited |",
        "",
        "## Indexes",
        "",
        "| Index | Definition |",
        "|---|---|",
    ]
    for statement in schema.INDEXES:
        name = statement.split(" IF NOT EXISTS ")[1].split(" ON ")[0]
        target = statement.split(" ON ")[1].split("(")[0]
        columns = statement.split("(", 1)[1].rstrip(")").replace(" DESC", "")
        lines.append(f"| `{name}` | `{target}({columns})` |")
    lines.append("")

    for table in schema.TABLES:
        lines.append(f"## {table}")
        lines.append("")
        if table in NOTES:
            lines.append(NOTES[table])
            lines.append("")
        lines.append("| Column | Declared | SQLite | Key |")
        lines.append("|---|---|---|---|")
        for name, declaration, declared in schema.columns(table):
            sqlite_type = declaration.split()[0]
            if "PRIMARY KEY" in declaration:
                sqlite_type += " PRIMARY KEY"
            if "AUTOINCREMENT" in declaration:
                sqlite_type += " AUTOINCREMENT"
            if declaration.endswith("COLLATE NOCASE"):
                sqlite_type += " COLLATE NOCASE"
            key = "yes" if "PRIMARY KEY" in declaration else ""
            lines.append(f"| `{name}` | {declared} | {sqlite_type} | {key} |")
        lines.append("")

    lines += [
        "## Built-in user groups",
        "",
        "| group_id | Name | group_rights |",
        "|---|---|---|",
    ]
    for group_id, name, rights in schema.BUILTIN_GROUPS:
        lines.append(f"| {group_id} | {name} | `{rights}` |")
    lines.append("")
    return "\n".join(lines)


def api_markdown() -> str:
    lines = [
        "# API reference",
        "",
        "Generated by `server/src/tools/export_docs.py` from "
        "`server/src/openapi_spec.py`; do not edit it by hand - rerun `make docs` "
        "after an API change, which also refreshes `docs/openapi.json`.",
        "",
        f"This list has {len(openapi_spec.ENDPOINTS)} operations. Every response is JSON "
        "(except the trackback ping and RSS); failures return "
        '`{"ok": false, "error": "<lang key>"}`.',
        "",
        "| Method | Path | Summary | Access |",
        "|---|---|---|---|",
    ]
    for method, path, operation in openapi_spec.ENDPOINTS:
        summary = operation.get("summary", "")
        path = openapi_spec.asp_path(path)
        if operation.get("security"):
            permission = "login required"
        elif "admin" in operation.get("tags", []):
            permission = "admin"
        else:
            permission = "public"
        lines.append(f"| {method.upper()} | `{path}` | {summary} | {permission} |")

    lines += [
        "",
        "## Permission model",
        "",
        "- `blog_UserGroup.group_rights` is five digits: `view` / `post` / `edit` / "
        "`delete` / `upload`.",
        "- `0` means no access, `1` only the user's own objects, `2` and above every "
        "object.",
        "- Article visibility: `log_mode` 1 public, 2 needs login, 3 needs `view>=2`, "
        "4 needs `view>=3`; hidden categories need `view>=2`, and authors can always "
        "read their own articles.",
        "- The admin backend additionally requires a second login through "
        "`POST /api/admin/login`.",
        "",
        "## Write endpoints open to guests",
        "",
        "Visitors without an account may still comment and sign the guestbook. The "
        "handlers enforce the guest group rights:",
        "",
        "- `POST /api/articles/{id}/comments`",
        "- `POST /api/guestbook`",
        "- `GET|POST /trackback/{id}` (pings arrive from other sites)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    database_path = DOCS_DIR / "database.md"
    api_path = DOCS_DIR / "api.md"
    database_path.write_text(database_markdown(), encoding="utf-8")
    api_path.write_text(api_markdown(), encoding="utf-8")
    print(f"wrote {database_path}")
    print(f"wrote {api_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
