"""English strings, ported from ``lang/blog.asp``.

Keys are kept identical to the original language array so the ASP sources and
this port can be diffed directly. The admin strings from ``lang/admin.asp``
are added later (M5).
"""

from __future__ import annotations

from typing import Final

STRINGS: Final[dict[str, str]] = {
    "view_user_article": "View All Articles from this User",
    "view_user_comment": "View All Comments from this User",
    "index": "Index",
    "guestbook": "Guestbook",
    "announcement": "Announcement",
    "homepage": "Homepage",
    "toggle_sidebar": "Toggle Sidebar",
    "stats": "Statistics",
    "user_panel": "User Panel",
    "category": "Category",
    "categories": "Categories",
    "calendar": "Calendar",
    "articles": "Articles",
    "read_more": "Read More...",
    "views": "Views",
    "visitors": "Visitors",
    "online_user": "Online User",
    "reg_users": "Registered Users",
    "permalink": "Permalink",
    "comments": "Comments",
    "trackbacks": "Trackbacks",
    "recent_articles": "Recent Articles",
    "recent_comments": "Recent Comments",
    "search": "Search",
    "links": "Links",
    "trackback": "Trackback",
    "view_mode": "View Mode",
    "normal": "Normal",
    "list": "Article List",
    "no_article": "There is no article to display.",
    "enabled": "Enabled",
    "disabled": "Disabled",
    "login": "Login",
    "username": "Username",
    "scode": "Security Code",
    "password": "Password",
    "auto_login": "Auto Login",
    "login_done": "You have logged in.",
    "login_already": "You have already logged in.",
    "login_error": "Errors found while login:",
    "user_not_found": "User can not be found.",
    "username_invalid": "Username is invalid. (3-24 chars, no special chars)",
    "password_invalid": "Password is invalid. (6-16 chars)",
    "scode_invalid": "Security Code is invalid. (4 digits number)",
    "login_fail": "Username and Password do not match. Login failed.",
    "login_fail_ban":
        "You have failed in login for 3 times. Please wait 3 minutes before trying again.",
    "form_incomplete": "Please fill in all required fields.",
    "login_as": "You have logged-in as",
    "administration": "Administration",
    "edit_profile": "Edit Profile",
    "new_article": "New Article",
    "logout": "Logout",
    "logout_done": "You have logged out.",
    "register": "Register",
    "submit": "Submit",
    "new": "New",
    "view": "View",
    "post": "Post",
    "move": "Move",
    "edit": "Edit",
    "delete": "Delete",
    "save": "Save Content",
    "save_change": "Save Changes",
    "reset": "Reset Form",
    "ok": "Ok",
    "cancel": "Cancel",
    "yes": "Yes",
    "no": "No",
    "unkown": "Unkown",
    "none": "None",
    "back": "Back",
    "code": "Code",
    "image": "Image",
    "url": "URL",
    "text": "Text",
    "bytes": "Bytes",
    "kb": "Kb",
    "mb": "Mb",
    "gb": "Gb",
    "na": "N/A",
    "total": "Total",
    "items": "Items",
    "confirm_delete_article": "Are you sure to delete this article?",
    "confirm_delete_comment": "Are you sure to delete this comment?",
    "confirm_delete_trackback": "Are you sure to delete this trackback?",
    "confirm_delete_user": "Are you sure to delete this user?",
    "post_time": "Post Time",
    "title": "Title",
    "author": "Author",
    "content": "Content",
    "mode": "Mode",
    "public": "Public",
    "draft": "Draft",
    "hidden": "Hidden",
    "private": "Private",
    "locked": "Locked",
    "no_rights_view": "You don't have the permission to view this Article.",
    "selected": "Selected Content",
    "smilies": "Smilies",
    "quote": "Quote",
    "comm_hidden": "Hidden Comment",
    "reg_now": "Register Now",
    "post_comment": "Post Comment",
    "edit_comment_on": "Edit Comment on",
    "length_invalid": "The Content Length is Invalid.",
    "wordfilter_block": "The Content is Blocked by the Word Filter.",
    "flood_control":
        "Spamming is not allowed. Please wait a few seconds before trying again.",
    "comment_not_found": "Comment can not be Found.",
    "comment_save_done": "Your Comment is Saved.",
    "comment_delete_done": "Comment Entry is Deleted.",
    "done": "Done",
    "error": "Error",
    "invalid_parameter": "Invalid parameters. Please visit this page via a valid link.",
    "no_rights": "You don't have the permission for this operation.",
    "goback": "[Click Here To Go Back]",
    "redirect": "[Click Here To Redirect Immediately]",
    "user_info": "User Profile",
    "user_group": "User Group",
    "gender": "Gender",
    "gender0": "Unkown",
    "gender1": "Male",
    "gender2": "Female",
    "avatar": "Avatar",
    "email": "Email",
    "ip": "IP",
    "last_visit": "Last Visit",
    "edit_password_req": "Please enter your password to save changes",
    "new_password": "New Password",
    "old_password_invalid": "Please Input your Current Password.",
    "profile_updated": "User Profile Updated.",
    "user_deleted": "User Deleted.",
    "reg_agreement": "User Agreement",
    "reg_agreement_text":
        "<p>If you agree with the following rules then click on the 'I Agree' button "
        "at the bottom of the page if not click on the 'I Dont Agree' button.</p>"
        "<p>You agree not to use this blog to post any material which is vulgar, "
        "defamatory, inaccurate, harassing, hateful, threatening, invading of others "
        "privacy, sexually oriented, or violates any laws. You also agree that you "
        "will not post any copyrighted material that is not owned by yourself or the "
        "owners of the content.</p><p>You remain solely responsible for the content "
        "of your messages, and you agree to indemnify and hold harmless this blog "
        "and their agents with respect to any claim based upon any post you may "
        "make. We also reserve the right to reveal whatever information we know "
        "about you in the event of a complaint or legal action arising from any "
        "message posted by yourself.</p><p>By registering to use this blog you meet "
        "the above criteria and agree to abide by all of the above rules and "
        "policies.<br /></p>",
    "reg_agree": "I Agree",
    "reg_decline": "Decline",
    "reg_disabled": "User registration is disabled.",
    "reg_already": "You have already registered.",
    "reg_title": "User Registration",
    "username_req": "Must between 3 to 24 chars",
    "password_req": "Must between 6 to 16 chars",
    "repassword": "Confirm Password",
    "repassword_req": "Must match the password above",
    "scode_req": "Please Enter the Security Code",
    "email_hide": "Hide my Email address",
    "email_invalid": "Email Address is invalid. You can leave it blank.",
    "user_exist": "Username is already been taken. Please choose another one.",
    "reg_error": "Errors found in registration:",
    "reg_done":
        "Thanks for your registration.<br /><br />You'll be redirected to the Index "
        "page and login now.",
    "article_not_found": "Article can not be found.",
    "edited_by": "Last Modified By ",
    "at": ", at ",
    "comment_feed": "Comments Feed",
    "trackback_url": "Trackback URL",
    "no_comment": "There is no comment on this article.",
    "hidden_comment": "This is a hidden comment.",
    "show_all": "Show All",
    "toggle_order": "Toggle Order",
    "comment_disabled": "You can't post comment on this article.",
    "quote_from": "Quotes From",
    "show_media": "Click Here to Show/Hide Media",
    "font_size": "Font Size",
    "large": "Large",
    "medium": "Medium",
    "small": "Small",
    "set_to_current": "Set to Current Time",
    "select_category": "Select Category",
    "e_html": "Use HTML",
    "e_ubb": "Enable UBB Codes",
    "e_autourl": "Auto Convert URL",
    "e_image": "Show Images",
    "e_media": "Show Media",
    "e_smilies": "Show Smilies",
    "attachment": "Attachment",
    "upload": "Upload",
    "upload_done": "File is Uploaded.",
    "upload_object_fail": "Failed to Create Object or Get File Data.",
    "file_size_limit": "File Size exceeds the Limit.",
    "file_type_limit": "Invalid File Type.",
    "file_write_fail": "Failed to write file.",
    "click_download": "Click Here To Download",
    "invalid_cat": "Invalid Category.",
    "invalid_mode": "Invalid Article Mode.",
    "title_invalid": "The Title is Invalid.(1-255 chars)",
    "content_blank": "The Content is Blank.",
    "update_done": "Article Content Updated.",
    "save_done": "Article Saved.",
    "delete_done": "Article Deleted.",
    "trackback_done": "Trackback is Done.",
    "trackback_error": "Trackback Error",
    "create_object_fail_xmlhttp":
        "Create Object Failed(Trackback have not been sent)",
    "create_object_fail_xmldom":
        "Create Object Failed(Trackback might already saved)",
    "server_no_response": "Target has no response.(Trackback might already saved)",
    "parse_error": "Error occured when parsing response.(Trackback might already saved)",
    "trackback_not_found": "Trackback can not be Found.",
    "trackback_delete_done": "Trackback Deleted.",
    "rss_feed": " RSS Feed",
    "comment_on": "Comment on",
    "recent_visitors": "Recent Visitors",
    "browser": "Browser",
    "os": "OS",
    "timestamp": "Time Stamp",
    "referer": "Referer",
    "gbook_disabled": "GuestBook Disabled",
    "no_entry": "No Entry to display",
    "entries": " Entries",
    "reply": "Reply",
    "edit_gbook_entry": "Edit/Reply GuestBook Entry",
    "day": "Day",
    "month": "Month",
    "year": "Year",
    "weekday_0": "Sunday",
    "weekday_1": "Monday",
    "weekday_2": "Tuesday",
    "weekday_3": "Wednesday",
    "weekday_4": "Thursday",
    "weekday_5": "Friday",
    "weekday_6": "Saturday",
    "month_1": "January",
    "month_2": "February",
    "month_3": "March",
    "month_4": "April",
    "month_5": "May",
    "month_6": "June",
    "month_7": "July",
    "month_8": "August",
    "month_9": "September",
    "month_10": "October",
    "month_11": "November",
    "month_12": "December",
    "weekday_abbr_0": "Su",
    "weekday_abbr_1": "Mo",
    "weekday_abbr_2": "Tu",
    "weekday_abbr_3": "We",
    "weekday_abbr_4": "Th",
    "weekday_abbr_5": "Fr",
    "weekday_abbr_6": "Sa",
    "month_abbr_1": "Jan",
    "month_abbr_2": "Feb",
    "month_abbr_3": "Mar",
    "month_abbr_4": "Apr",
    "month_abbr_5": "May",
    "month_abbr_6": "Jun",
    "month_abbr_7": "Jul",
    "month_abbr_8": "Aug",
    "month_abbr_9": "Sep",
    "month_abbr_10": "Oct",
    "month_abbr_11": "Nov",
    "month_abbr_12": "Dec",
    # --- admin strings, ported from lang/admin.asp ---
    "admin_login": "Administrator Login",
    "admin_panel": "Administration",
    "general_info": "General Information",
    "clean_cache": "Clean Cache",
    "open_site": "Open Site",
    "close_site": "Close Site",
    "server_software": "Server Software",
    "server_ip": "Server IP",
    "server_time": "Server Time",
    "app_path": "Application Path",
    "script_engine": "Script Engine",
    "req_scriptengine": "Require Script Engine 5.5+ for better functionality",
    "obj_fso": "Scripting.FileSystemObject Object",
    "req_obj_fso": "Required for Upload and Web File Management",
    "obj_stream": "ADODB.Stream Object",
    "req_obj_stream": "Required for File Upload",
    "obj_xmlhttp": "MSXML2.ServerXMLHTTP Object",
    "req_obj_xmlhttp": "Required for Sending Trackback",
    "obj_xmldom": "Microsoft.XMLDOM Object",
    "req_obj_xmldom": "Required for Parsing Trackback Response",
    "global_settings": "Global Settings",
    "blog_title": "Blog Title",
    "blog_desc": "Blog Description",
    "blog_base_url": "Blog Base URL",
    "blog_logo_image": "Blog Logo Image",
    "webmaster_name": "WebMaster Name",
    "webmaster_email": "WebMaster Email",
    "language_code": "Language Code",
    "language_code_ref": "Language Code Reference for RSS",
    "default_view": "Default View Mode",
    "article_per_page": "Articles Per Page",
    "entry_per_page": "List Entry Per Page",
    "apply_comm_tb": "Applied on Comment/Trackback List Page",
    "comment_per_page": "Comments Per Page",
    "comment_time_order": "Comments Sort By",
    "time_asc": "Post Time Ascending",
    "time_desc": "Post Time Descending",
    "apply_article_page":
        "Applied on Article display page. Set to 0 to disable.",
    "show_tb_w_comm": "Show Trackbacks<br/>with Comments",
    "on_comm_top": "Before Comments",
    "on_comm_bottom": "After Comments",
    "dynamic_calendar": "Dynamic Calendar",
    "cal_more_query":
        "Require 1 more DB Query when the Article is not in current month",
    "enable_split": "Article Auto-Split",
    "split_at": "Auto-Split Article Content at",
    "enable_reg": "Enable User Register",
    "enable_scode": "Enable Security Code",
    "enable_trackback": "Enable Trackback",
    "incoming": "Incoming",
    "outgoing": "Outgoing",
    "enable_comment": "Enable Comment",
    "max_comment_length": "Max Comment Length",
    "enable_guestbook": "Enable GuestBook",
    "gbook_page_size": "GuestBook Page Size",
    "chars": "Characters",
    "for_forms": "For the Smilies List on the side of Message Forms",
    "style_sheet": "CSS Style Sheet",
    "image_folder": "Images Folder",
    "smilies_folder": "Smilies Images Folder",
    "smilies_per_row": "Show Smilies Per Row",
    "between_posts":
        'Seconds Between Two Posts <span class="comment-text">'
        "(Affects Posting Comments)</span>",
    "record_visitor": "Record Visitors",
    "visitors_not_affect":
        'Visitors <span class="comment-text">'
        "(Disable this will not affect the Internal Counter)</span>",
    "enable_upload": "Enable Upload",
    "upload_size": "Upload Size Limit",
    "upload_path": "Upload Path",
    "upload_type": "Upload File Types",
    "seperate_by": "Seperated By ,",
    "order": "Order",
    "delete_cat": "Delete Selected Categories",
    "move_cat": "Move Articles in Selected Categories",
    "select_target_cat": "Select the Target Category",
    "from_cat": "From Category",
    "to_cat": "To Category",
    "execute": "Execute",
    "delete_cat_note":
        "Delete a category will also delete all articles, comments, "
        "trackbacks in that category.",
    "self": "Self",
    "delete_group": "Delete User Group",
    "delete_group_note":
        "Delete a User Group will also delete all users in this group",
    "delete_smilies": "Delete Selected Smilies",
    "word_filter": "Word Filter",
    "regexp": "RegExp",
    "replace": "Replace",
    "block": "Block",
    "delete_wordfilter": "Delete Selected WordFilter",
    "database": "Database",
    "db_path": "Database Path",
    "db_size": "Database Size",
    "backup": "Backup",
    "compact": "Compact",
    "backup_list": "Backup File List",
    "restore": "Restore",
    "confirm_restore": "Are you sure to restore from this file?",
    "check_exist": "Checking Database File existence",
    "close_conn": "Closing Database Connection",
    "compact_db": "Compacting Database",
    "copy_to_backup": "Copying to backup file",
    "rename_db_file": "Renaming Temporary Database File",
    "restore_db": "Restoring Database File",
    "error_occured": "Error occured",
    "op_result": "Operation Result",
    "op_done": "Operation Done",
    "attachments": "Attachments",
    "parent_folder": "Parent Folder..",
    "confirm_delete_file": "Are you sure to delete this file?",
    "confirm_delete_folder": "Are you sure to delete this folder?",
    "delete_folder_note": "You can only delete empty Folders",
    "show_announce": "Show Announcement",
    "misc": "Miscellaneous",
    "resync_global_stats": "Resync Global Statistic",
    "processed": "Processed ",
    "resync_cat_stats": "Resync Category Statistic",
    "resync_article_stats": "Resync Article Statistic",
    "resync_user_stats": "Resync User Statistic",
    "clean_user": "Clean Inactive User Account",
    "clean_visitor_record": "Clean Visitor Counter Records",
    "clean_gbook_record": "Clean GuestBook Entries Older Than 30 Days",
    "resync_note": "Some of these operations may take a long time while running.",
}


def text(key: str, default: str = "") -> str:
    """Return a language string by key."""
    return STRINGS.get(key, default or key)
