"""Scenario runner for the full business API end to end tests."""

from __future__ import annotations

import importlib
import time
from pathlib import Path

import context as context_module

SCENARIOS = (
    "auth",
    "articles",
    "comments",
    "guestbook",
    "trackback",
    "users",
    "admin",
    "feeds",
    "upload",
    "urls",
)

CASES_TEMPLATE = """# Full business API E2E case list

Generated by `server/tests/api_e2e/runner.py` on every run (`make test_api_full`);
do not edit by hand. The scenarios live in `server/tests/api_e2e/scenarios/`.

| Scenario | Case | Description |
|---|---|---|
{rows}
"""


def load(name: str):
    return importlib.import_module(f"scenarios.{name}")


def write_cases(path: Path, ctx, elapsed: float) -> None:
    rows = []
    for name in SCENARIOS:
        module = load(name)
        for case, description in module.CASES:
            rows.append(f"| {name} | `{case}` | {description} |")
    path.write_text(
        CASES_TEMPLATE.format(
            rows="\n".join(rows),
        ),
        encoding="utf-8",
    )


def run(app_module, data_dir, *, only=None, cases_path: "Path | None" = None) -> int:
    ctx = context_module.Context(app_module, data_dir)
    started = time.time()
    selected = [name for name in SCENARIOS if not only or name in only]

    for name in selected:
        module = load(name)
        before = len(ctx.failures)
        print(f"\n== {name}: {module.DOC}")
        try:
            module.run(ctx)
        except Exception as exc:  # keep going, report at the end
            ctx.failures.append(f"{name}: {type(exc).__name__}: {exc}")
        added = len(ctx.failures) - before
        print(f"   {'OK' if added == 0 else 'FAIL'}  ({added} failures)")

    elapsed = time.time() - started
    if cases_path is not None:
        write_cases(cases_path, ctx, elapsed)
        print(f"\ncase list updated: {cases_path}")

    print(f"\n{ctx.checks} assertions, {len(ctx.failures)} failures in {elapsed:.1f}s")
    if ctx.failures:
        print("\nfailures:")
        for failure in ctx.failures:
            print(f"  - {failure}")
        return 1
    print("all green")
    return 0
